#ifndef MT_MODIFIER_H
#define MT_MODIFIER_H

typedef enum MtModifier
{
  MT_MODIFIER_NONE,
  MT_MODIFIER_PALM_MUTE,
  MT_MODIFIER_HARMONIC,
  MT_MODIFIER_VIBRATO
} MtModifier;

#endif // MT_MODIFIER_H
